### ISSUE TITLE
no turtle shells!

### ISSUE THREAD

**Issue by derekeder** [codeforamerica/super-mayor#2]
<img width="1271" alt="screen shot 2018-06-19 at 8 33 36 pm" src="https://user-images.githubusercontent.com/919583/41632539-0be36228-7400-11e8-8b08-0a200e7a6ba2.png">

Looks like the `status` field is now `undefined`, which is tripping a javascript error. The result is no shells to jump over!

**Comment by bensheldon** [comment]
Thanks! I’ll look into what’s causing this.

**Comment by bensheldon** [comment]
I fixed the issue with the code. Now I have to figure out how to re-deploy the 6 year app to Heroku 😭

**Comment by derekeder** [comment]
Ah man - good luck!

**Comment by bensheldon** [comment]
I dockerized it and pushed it up to Heroku 🎉  It's working: http://supermayor.io/

... though for some reason it doesn't seem like it loads more items unless the chrome devtools is open. eh 😞

**Comment by bensheldon** [comment]
Ohhh, it's because of chrome autoplay: Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

OK, I'm gonna ignore that for now.

**Comment by derekeder** [comment]
It's fixed! Chicago, and I, thank you!

<img width="1276" alt="screen shot 2018-06-29 at 5 02 46 pm" src="https://user-images.githubusercontent.com/919583/42116758-643fe3e0-7bbe-11e8-9c82-8f37e538833b.png">

**Comment by bensheldon** [comment]
\o/
